doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Domain/DoctrineMigrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: App\Domain\DoctrineMigrations
