version: "3.1"

services:
    # Core configuration
    php-fpm:
        container_name: ${CONTAINER_NAME}_php-fpm
        build: .
        environment:
          BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
          BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
        ports:
            - '${PHP_PORT}:9000'
        volumes:
            - './:${WORKPATH}:delegated'
        restart: always

    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx
        ports:
            - '${NGINX_PORT}:80'
        links:
            - php-fpm
        volumes:
            - './:${WORKPATH}:delegated'
            - './docker/nginx/conf/core/nginx.conf:/etc/nginx/conf/nginx.conf:ro'
            - './docker/nginx/conf/development:/etc/nginx/conf.d:ro'
            # - './docker/nginx/conf/production:/etc/nginx/conf.d:ro' -> Uncomment this line for production.
            - './docker/nginx/logs/:/var/log/nginx'
        restart: always

    # MariaDB Configuration
    mariadb:
        container_name: ${CONTAINER_NAME}_mariadb
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MYSQL_USER: ${MARIADB_USER}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_DATABASE: ${MARIADB_NAME}
        ports:
            - '${MARIADB_PORT}:3306'
        volumes:
            - 'mariadb_behat:/var/lib/mysql:rw'

    # Performances configuration
    blackfire:
        container_name: ${CONTAINER_NAME}_blackfire
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
            BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID}'
            BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN}'
        links:
            - php-fpm
        volumes:
            - './:${WORKPATH}:rw'
        restart: always

volumes:
    mariadb_behat: